name: Verify CHANGELOG.md Updated
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/**'
      - 'src/data/**' # Ignore d2ai updates

jobs:
  changelog:
      if: github.event.pull_request.draft == false
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          # https://github.community/t/can-workflow-changes-be-used-with-pull-request-target/178626
          # Why this can be dangerous https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
          with:
            ref: ${{github.event.pull_request.head.ref}}
            repository: ${{github.event.pull_request.head.repo.full_name}}

        - name: Labeled to Changelog-None?
          id: haslabel
          uses: docker://agilepathway/label-checker@v1.2.6
          with:
            all_of: 'Changelog-None'
            allow_failure: true

        - name: Remove other Changelog Labels if Changelog-None Applied
          if: steps.haslabel.outputs.label_check == true
          uses: mondeja/remove-labels-gh-action@v1
          with:
            labels: |
              Changelog-Applied
              Changelog-Missing
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Check for updates
          uses: dorny/paths-filter@v2
          id: filters
          with:
            filters: |
              changelog: 'docs/CHANGELOG.md'

        - name: porcelain check
          uses: dorny/paths-filter@v2
          id: porcelain
          with:
            base: HEAD
            filters: |
              changed:
                - '**'

        - name: No CHANGELOG.md Update (Remove Applied)
          if: (steps.filters.outputs.changelog == 'true' && steps.haslabel.outputs.label_check != true)
          uses: mondeja/remove-labels-gh-action@v1
          with:
            labels: |
              Changelog-Applied
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: No CHANGELOG.md Update (Add Missing)
          if: (steps.porcelain.outputs.changed == 'true' && steps.filters.outputs.changelog == 'true' && steps.haslabel.outputs.label_check != true)
          uses: christianvuerings/add-labels@v1
          with:
            labels: |
              Changelog-Missing
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: CHANGELOG.md Updated (Remove Missing)
          if: (steps.filters.outputs.changelog == 'true' && steps.haslabel.outputs.label_check != true)
          uses: mondeja/remove-labels-gh-action@v1
          with:
            labels: |
              Changelog-Missing
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: CHANGELOG.md Updated (Add Applied)
          if: (steps.filters.outputs.changelog == 'true' && steps.haslabel.outputs.label_check != true)
          uses: christianvuerings/add-labels@v1
          with:
            labels: |
              Changelog-Applied
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


