name: 'Check spelling'
on: # rebuild on any PRs
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          strict: false
          config: 'cspell.json'
          incremental_files_only: true
