name: PR Test & Lint

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Jest Test
        run: yarn jest

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: junit.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Cache ESLint
        uses: actions/cache@v3
        env:
          cache-name: cache-eslint
        with:
          path: ~/.eslintcache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Save ESLint Report JSON
        run: yarn lint-report:cached
        continue-on-error: true

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: lint-results
          path: eslint.results.json